### ISSUE TITLE
Literal changes

### ISSUE THREAD

**Issue by joycarpediem** [akvo/IDH-IDC#196]

**Comment by wayangalihpratama** [comment]
- [Info box and texts for graphs: Information boxes per Income Driver on input page have to be aligned with the definition on the main landing page (after login). (see F11)](https://app.asana.com/0/1205513346619877/1206886404738043/f)

**Comment by wayangalihpratama** [comment]
- [TASK 2: Sensitivity analysis intro](https://app.asana.com/0/0/1206977099606935/f)

**Comment by wayangalihpratama** [comment]
- [Update Descriptions for "What are the results for the different segments in the current scenario?"](https://app.asana.com/0/1205513346619877/1206886404738229/f)
