### ISSUE TITLE
Misc changes 

### ISSUE THREAD

**Issue by joycarpediem** [akvo/IDH-IDC#95]

**Comment by wayangalihpratama** [comment]
- [Graphs: Please make sure all boxes are visible on screen. Here is an example where info box is out of screen and therefore not visible. ](https://app.asana.com/0/1205513346619877/1206886404738077/f)

**Comment by wayangalihpratama** [comment]
- https://app.asana.com/0/1205513346619877/1206886404738202/f

**Comment by wayangalihpratama** [comment]
- https://app.asana.com/0/1205513346619877/1206886404738037/f

**Comment by wayangalihpratama** [comment]
- [Info box and texts for graphs: Some boxes are empty (mentioned related to input page) and therefore perceived to be not working. (see F11)](https://app.asana.com/0/1205513346619877/1206886404738041/f)

**Comment by wayangalihpratama** [comment]
- [Create page: Land Unit: Provide option for Square feet, Square meter as well. ](https://app.asana.com/0/1205513346619877/1206886404738333/f)

**Comment by wayangalihpratama** [comment]
- [Explore how to download the charts, default is only graph](https://app.asana.com/0/1205513346619877/1206990557006407/f)
